### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by aksalj** [Wanekeya/Simple-PHP-and-MySQL-HTMLL-Email-subscribe-for-localhost#1]
Repository name is too looong! What the hell is `Simple-PHP-and-MySQL-HTMLL-Email-subscribe-for-localhost`? :angry: How about `php-email-subscribe`? Or just `email-subscribe`?

**Comment by Wanekeya** [comment]
Huh..Sorry man, it's actually a guide for someone so couldn’t avoid it











From: Salama AB
Sent: ‎Tuesday‎, ‎July‎ ‎21‎, ‎2015 ‎7‎:‎25‎ ‎PM
To: Wanekeya/Simple-PHP-and-MySQL-HTMLL-Email-subscribe-for-localhost





Repo name is too looong  :angry:

**Comment by aksalj** [comment]
:ok_hand: :+1:
